services:
  - type: web
    name: pulsemed-backend
    env: node
    plan: free
    region: singapore
    buildCommand: npm install && cd backend && npm install
    startCommand: cd backend && node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
